x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  resource-labels:
    image: lblod/resource-label-service:0.3.1
    restart: always
    environment:
      DEFAULT_LANGUAGE: 'nil'
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql
    logging: *default-logging
  uri-info:
    image: redpencil/mu-uri-info-service:feature-query-without-aplication-graph
    environment:
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
    environment:
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql      
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging
    ports:
      - 8890:80
    networks:
      default:
        aliases:
          - backend      
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config:Z
    labels:
      - "logging=true"
    logging: *default-logging
  
  frontend:
    build: ./frontend-metis-ghent
    environment:
      EMBER_METIS_BASE_URL: "https://qa.stad.gent/"
      EMBER_METIS_SERVICE_BASE: "/data"
    labels:
      - "logging=true"
  virtuoso:
    image: docker.io/redpencil/virtuoso:1.2.0-rc.1
    volumes:
      - ./data/db/:/data/:Z
  
