services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - identifier
  virtuoso:
#    ports:
#      - "8890:8890"
    volumes:
      - ./data/dev-data:/data/toLoad
      - ./data/logs:/data/logs
  dispatcher:
    environment:
      BASE_URI: "https://qa.stad.gent"
  frontend:
    environment:
      EMBER_METIS_BASE_URL: "https://qa.stad.gent/"
  cool-uris:
#    ports:
#      - "8080:8080"
