services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - identifier
  virtuoso:
    volumes:
      - ./data/dev-data:/data/toLoad
