x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  resource-labels:
    image: lblod/resource-label-service:0.3.1
    restart: always
    environment:
      DEFAULT_LANGUAGE: 'nil'
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql
    logging: *default-logging
  uri-info:
    image: redpencil/mu-uri-info-service:feature-query-without-aplication-graph
    environment:
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
    environment:
      MU_SPARQL_ENDPOINT: https://stad.gent/sparql      
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
      MU_SPARQL_TIMEOUT: "10000"
      MU_SPARQL_UPDATE_TIMEOUT: "10000"
    labels:
      - "logging=true"
    logging: *default-logging
    ports:
      - 8200:80
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging: *default-logging
  
  frontend:
    build: ./frontend-metis-ghent
    environment:
      EMBER_METIS_BASE_URL: "https://stad.gent/"
    links:
      - identifier:backend
    labels:
      - "logging=true"
  sparqlproxy:
    image: nginx:alpine
    volumes:
      - ./config/sparql-proxy.conf:/etc/nginx/conf.d/default.conf:ro
